string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(stage "${OUTPUT_ROOT}/missing-ocr-${suffix}")
file(MAKE_DIRECTORY "${stage}/test-fixtures")
file(COPY "${TEST_BINARY}" DESTINATION "${stage}")
file(COPY "${FIXTURE}" DESTINATION "${stage}/test-fixtures")
if(WITH_RUNTIME)
  file(COPY "${OCR_RUNTIME}" DESTINATION "${stage}")
endif()
set(argument --missing-assets)
if(WITH_DETECTOR)
  file(MAKE_DIRECTORY "${stage}/models")
  file(COPY "${DETECTOR_MODEL}" DESTINATION "${stage}/models")
  set(argument --missing-recognizer)
endif()
execute_process(COMMAND "${stage}/BundledOcrTests.exe" ${argument}
  WORKING_DIRECTORY "${stage}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "OCR fallback failed (${result}): ${output} ${error}")
endif()
message(STATUS "${output}")
